<!--- Universal Analytics Start -->
<?php $this->JS = Mage::getSingleton('baua/js'); ?>
<?php $itemsCollection = Mage::getSingleton('checkout/session')->getQuote()->getItemsCollection(); ?>
<?php $_helper = Mage::helper('baua') ?>
<?php $_debug = $_helper->isDebugEnabled(); ?>
<?php $productArray = array(); ?>
<?php if($_helper->isActive()): ?>
    <?php foreach ($itemsCollection as $item) :?>
        <?php $result = Mage::getModel('baua/monitor')->generateProductData($item); ?>
        <?php if($result != null) : ?>
            <?php $productArray[] = $this->JS->generateGoogleJS('ec:addProduct', $result) . "\n"; ?>
        <?php endif; ?>
    <?php endforeach; ?>


    <script type="text/javascript">

        <?php foreach($productArray as $product) : ?>
            <?php echo $product; ?>
        <?php endforeach; ?>
        <?php echo $this->JS->generateGoogleJS('ec:setAction', 'checkout', Array('step' => 1)); ?>
        <?php echo $this->JS->generateGoogleJS('send', 'pageview'); ?>

        /**
         * For some reason, magento never actually sets 'login' as a
         * step, so we need to basically force it here.
         */
        checkout.setMethodParent = checkout.setMethod;
        checkout.setMethod = function() {
            this.currentStep = 'login';
            this.setMethodParent();
        };

        /**
        * This overrides the checkout.gotoSection to perform the ga push.
        * @type {gotoSection}
        */
        checkout.gotoSectionparent = checkout.gotoSection;
        checkout.gotoSection = function(section, reloadProgressBlock) {
            try {
                var curStep = this.steps.indexOf(this.currentStep)+1;
                var nextStep = this.steps.indexOf(section)+1;
                var option = undefined;

                <?php if ($_debug): ?>
                    console.log("ga gotoSection(" + section + ") from " + this.currentStep);
                <?php endif; ?>

                if (this.currentStep == 'login') {
                    option = this.method;
                }

                if (this.currentStep == 'shipping_method') {
                    option = $(shippingMethod.form).select('input[name="shipping_method"][checked]')[0];
                    option = (typeof option == 'undefined') ? null : option.value;
                }

                if (typeof option !== 'undefined') {
                    <?php if ($_debug): ?>
                        console.log("ga('ec:setAction', 'checkout_option', {step: " + curStep + ", option: '" + option + "'})");
                        console.log("ga('send', 'event', 'Checkout', 'Option')");
                    <?php endif; ?>

                    ga('ec:setAction', 'checkout_option', {
                        'step': curStep,
                        'option': option
                    });
                    ga('send', 'event', 'Checkout', 'Option');
                } else {
                    <?php if ($_debug): ?>
                        console.log("ga unrecognized step `" + this.currentStep + "`");
                    <?php endif; ?>
                }

                <?php if ($_debug): ?>
                    console.log("ga('ec:setAction', 'checkout', {step: " + nextStep + ", label: " + section + "})");
                <?php endif; ?>
                ga('ec:setAction','checkout', {'step': nextStep, 'label': section });
                <?php foreach($productArray as $product) : ?>
                <?php echo $product; ?>
                <?php endforeach; ?>
                <?php echo $this->JS->generateGoogleJS('send', 'pageview')?>
            } catch (e) {
                <?php if ($_debug): ?>
                try {
                    console.log("Google analytics code failed");
                    console.log(e);
                } catch(e2) {}
                <?php endif; ?>
            }

            if (reloadProgressBlock) {
                this.reloadProgressBlock(this.currentStep);
            }

            // Older versions of Magento are completely lacking the
            // currentStep variable, so we're re-implementing some of
            // that functionality here.
            this.currentStep = section;

            this.gotoSectionparent(section);
        };
    </script>

<?php endif ?>
<!--- Universal Analytics End -->
